import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import Workoutdetails from '../components/workoutdetails'
// interface workouts{
//   title:string,
//   reps:string,
//   load:string
// }
export default function Home() {
  const [workout, setWorkout]=useState('')
  const [reps, setReps]=useState('')
  const [load, setLoad]=useState('')
  const [workouts, setWorkouts]=useState(null)

  useEffect(()=>{
    const fetchWorkouts = async()=>{
      const response = await fetch('http://localhost:5000/api/workouts')
      const json = await response.json()
      if(response.ok){
        setWorkouts(json)
      }
    }
    fetchWorkouts()
  },[])

  const onSubmit = (e)=>{
    e.preventDefault()
    const data ={workout, reps, load}

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <div >
        <h1 className='text-2xl font-bold items-center flex justify-center'>Workout Buddy</h1>
        {/* <form 
        className='flex flex-col justify-center  items-center'
        onSubmit={onSubmit}>
        <h1>Enter Workout</h1>
        <input 
        onChange={(e)=>setWorkout(e.target.value)}
        
        className='w-1/2 border-black border'/>
        <h1>Enter Reps</h1>
        <input
        onChange={(e)=>setReps(e.target.value)}

        className='w-1/2 border-black border'/>
        <h1>Enter Load</h1>
        <input 
        onChange={(e)=>setLoad(e.target.value)}

        className='w-1/2 border-black border'/>
        </form> */}
        <h1>Your recent Workouts</h1>
      <div>
        {workouts && workouts.map((workout)=>(
        <div key={workout._id}>
          
          <Workoutdetails key={workout._id} workout={workout}/>
          </div>
          
      ))
    }
    </div>
      </div>
      <span className='flex justify-center items-center align-center'>
      <button className='border border-black '><Link href="./addworkout">Add Workout</Link></button>
      </span>
      
    </div>
  )
}
